name: Test Branch Name Checker action

on:
  pull_request:
    types: [opened]

jobs:
  branch_name:
    runs-on: ubuntu-latest
    name: Branch Name
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test action locally
        uses: ./
        with:
          branch_pattern: 'feature|bug|chore|hotfix'
          comment_for_invalid_branch_name: 'Ups! This branch name is not following the standards! You can see them here: https://github.com/AlbertHernandez'
          fail_if_invalid_branch_name: 'false'